name: color_run_tw
version: 0.0.1
description: A mobile-friendly web app with routing, responsive CSS, and (optional) Sass support.
author: Luke Chi
homepage: https://github.com/lukechi1219/ColorRunTw20150627

environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  google_maps: '>=3.0.0 < 3.1.0'
  route_hierarchical: '>=0.5.0 <0.7.0'
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=1.0.0 <2.0.0'
transformers:
- script_inliner
